

function matchArrays(obj1, googleDOc) {
    let matchedPairs = {};

    for (let key in obj1) {
        if (obj1[key] in googleDOc) {
            matchedPairs[key] = googleDOc[obj1[key]];
        } else {
            matchedPairs[key] = obj1[key];
        }
    }

    return matchedPairs;
}

let array1 = {  "createFood": "Create A New Food",}




let array2 = {
        "Home": "الصفحة الرئيسية",
        "Workout": "التمرين",
        "Nutrition": "التغذية",
        "Training": "التدريب",
        "Clear": "مسح",
        "Submit": "إرسال",
        "Close": "إغلاق",
        "Apply": "تطبيق",
        "Set": "مجموعة",
        "Weight": "الوزن",
        "Reps": "تكرارات",
        "Tempo": "وتيرة",
        "RPE": "RPE",
        "Rest Time": "وقت الراحة",
        "Add Set": "إضافة مجموعة",
        "Search your plan": "البحث في خطتك",
        "Nadena Library": "مكتبة نادينا",
        "MyLibrary": "مكتبتي",
        "Programs": "البرامج",
        "View Details": "عرض التفاصيل",
        "Workout Video": "فيديو التمرين",
        "Equipments Required": "المعدات المطلوبة",
        "Beginner": "مبتدئ",
        "Intermediate": "متوسط",
        "Expert": "خبير",
        "Yes": "نعم",
        "No": "لا",
        "Workout title": "عنوان التمرين",
        "Category": "الفئة",
        "Level": "المستوى",
        "Equipments": "المعدات",
        "Primary Muscle Group": "مجموعة العضلات الرئيسية",
        "Secondary Muscle Group": "مجموعة العضلات الثانوية",
        "Instruction": "التعليمات",
        "Upload Images": "تحميل الصور",
        "Upload Videos": "تحميل الفيديوهات",
        "Youtube Link": "رابط يوتيوب",
        "Free Library": "مكتبة مجانية",
        "Update": "تحديث",
        "Add": "إضافة",
        "Duplicate": "تكرار",
        "Edit": "تحرير",
        "Delete": "حذف",
        "Create New": "إنشاء جديد",
        "Plan & Package": "الخطة والباقة",
        "Choose Attachments": "اختيار المرفقات",
        "Upload Attachments": "تحميل المرفقات",
        "Attachments": "المرفقات",
        "Photo Library": "مكتبة الصور",
        "Take Photo": "التقاط صورة",
        "Take Video": "تسجيل فيديو",
        "Cancel": "إلغاء",
        "Search": "بحث",
        "Search Country Code": "البحث عن رمز الدولة",
        "No Data to show": "لا توجد بيانات لعرضها",
        "Male": "ذكر",
        "Female": "أنثى",
        "First Name": "الاسم الأول",
        "Last Name": "الاسم الأخير",
        "Email": "البريد الإلكتروني",
        "Date of birth": "تاريخ الميلاد",
        "Phone Number": "رقم الهاتف",
        "Personal Details": "التفاصيل الشخصية",
        "Contact Details": "بيانات الاتصال",
        "Specialization": "التخصص",
        "Join": "الانضمام",
        "Upload documentation": "تحميل الوثائق",
        "Optional": "اختياري",
        "Gender": "الجنس",
        "Mobile": "الهاتف المحمول",
        "Password": "كلمة المرور",
        "Confirm Password": "تأكيد كلمة المرور",
        "I agree to the": "أوافق على",
        "Terms and Conditions": "الشروط والأحكام",
        "Continue": "متابعة",
        "Video Library": "مكتبة الفيديو",
        "Description": "الوصف",
        "Details": "التفاصيل",
        "Days": "الأيام",
        "Add Days": "إضافة أيام",
        "Day": "اليوم",
        "Created": "تم الإنشاء",
        "Workout Days": "أيام التمرين",
        "Add Extra Day": "إضافة يوم إضافي",
        "Add Day Name": "إضافة اسم اليوم",
        "Edit Day Name": "تحرير اسم اليوم",
        "Add Programme Day Name": "إضافة اسم يوم البرنامج",
        "Choose Option": "اختيار الخيار",
        "Day Name": "اسم اليوم",
        "Add Exercises": "إضافة تمارين",
        "Manage Set": "إدارة المجموعة",
        "Manage Sets": "إدارة المجموعات",
        "Workouts": "التمارين",
        "Warmup": "التمهيد",
        "Cool down": "التبريد",
        "Duplicate Set": "تكرار المجموعة",
        "Add Extra Set": "إضافة مجموعة إضافية",
        "Extra Sets": "مجموعات إضافية",
        "Title": "العنوان",
        "Currency": "العملة",
        "Price": "السعر",
        "Discount": "الخصم",
        "Type": "النوع",
        "Select Image": "اختيار الصورة",
        "Select Video": "اختيار الفيديو",
        "Library": "المكتبة",
        "Package": "الباقة",
        "Plan": "الخطة",
        "Gym": "الصالة الرياضية",
        "Sunday": "الأحد",
        "Monday": "الاثنين",
        "Tuesday": "الثلاثاء",
        "Wednesday": "الأربعاء",
        "Thursday": "الخميس",
        "Friday": "الجمعة",
        "Saturday": "السبت",
        "Weeks": "الأسابيع",
        "Add Weeks": "إضافة أسابيع",
        "Add Program": "إضافة برنامج",
        "Week": "الأسبوع",
        "Duplicate Week": "تكرار الأسبوع",
        "Delete Week": "حذف الأسبوع",
        "off": "إيقاف مؤقت",
        "Video": "الفيديو",
        "Latest Plans": "آخر الخطط",
        "Latest Packages": "آخر الباقات",
        "See All": "عرض الكل",
        "Day Details": "تفاصيل اليوم",
        "Add Plan & Package": "إضافة خطة وباقة",
        "Program Details": "تفاصيل البرنامج",
        "Oops! No library found. All your library will be listed here": "عذرًا! لم يتم العثور على مكتبة. سيتم سرد جميع مكتباتك هنا",
        "Oops! Something went wrong": "عذرًا! حدث خطأ ما",
        "Oops! No library found. All your Program will be listed here": "عذرًا! لم يتم العثور على أي برنامج. سيتم سرد جميع برامجك هنا",
        "No Days found. under your Program days will be listed here": "لا توجد أي أيام. سيتم سرد أيام برنامجك هنا",
        "No Exercises found. under your day exercises will be listed here": "لا توجد تمارين. سيتم سرد تمارين يومك هنا",
        "No sets available": "لا توجد مجموعات متاحة",
        "No Weeks found. under your plan weeks will be listed here": "لا توجد أسابيع. سيتم سرد أسابيع خطتك هنا",
        "No plans available": "لا توجد خطط متاحة",
        "No program found. under your day programs will be listed here": "لا توجد برامج. سيتم سرد برامج يومك هنا",
        "Please choose a thumbnail image to display in listing": "يرجى اختيار صورة مصغرة لعرضها في القائمة",
        "Please choose a video": "يرجى اختيار فيديو",
        "Upload any attachment you wish to show to your customers": "قم بتحميل أي مرفق ترغب في عرضه لعملائك",
        "Please enter a title": "يرجى إدخال عنوان",
        "Please select category": "يرجى تحديد الفئة",
        "Please select level": "يرجى تحديد المستوى",
        "Please select equipements": "يرجى تحديد المعدات",
        "Please select primary muscle groups": "يرجى تحديد مجموعات العضلات الأساسية",
        "Please select secondary muscle groups": "يرجى تحديد مجموعات العضلات الثانوية",
        "Please enter a instruction": "يرجى إدخال تعليمات",
        "Please select free library": "يرجى اختيار مكتبة مجانية",
        "Please enter a valid URL": "يرجى إدخال رابط صحيح",
        "You can only upload image file with maximum size of 5 MB": "يمكنك تحميل ملف صورة فقط بحجم يصل إلى 5 ميجابايت",
        "Please enter your answer": "يرجى إدخال إجابتك",
        "Please enter your first name": "يرجى إدخال اسمك الأول",
        "Please enter your phone number": "يرجى إدخال رقم هاتفك",
        "Please enter a valid email": "يرجى إدخال بريد إلكتروني صحيح",
        "Email is required": "البريد الإلكتروني مطلوب",
        "Invalid date of birth": "تاريخ الميلاد غير صحيح",
        "Please select a gender": "يرجى تحديد الجنس",
        "Profile Updated": "تم تحديث الملف الشخصي",
        "Customer Profile Updated": "تم تحديث ملف العميل",
        "Please Select User Category": "يرجى تحديد فئة المستخدم",
        "Verify Email!": "تحقق من البريد الإلكتروني!",
        "Your account has been successfully created. Please verify your email address to continue further.": "تم إنشاء حسابك بنجاح. يرجى التحقق من عنوان البريد الإلكتروني للمتابعة",
        "Please enter a your mail id!!": "يرجى إدخال عنوان البريد الإلكتروني الخاص بك!",
        "Please enter your name.": "يرجى إدخال اسمك",
        "Please enter your last name.": "يرجى إدخال اسمك الأخير",
        "Password should contain minimum 8 characters!!": "يجب أن تحتوي كلم",
        "Please enter a password": "يرجى إدخال كلمة المرور",
        "Your passwords do not match.": "كلمات المرور غير متطابقة",
        "Please enter a confirm password": "يرجى إدخال تأكيد كلمة المرور",
        "Please accept terms and conditions to continue'": "يرجى قبول الشروط والأحكام للمتابعة",
        "Uploading in Progress": "جاري التحميل",
        "Attachment": "يرجى الانتظار أثناء تحميل المرفقات",
        "Please enter a description": "يرجى إدخال وصف",
        "Please enter no of days under this program": "يرجى إدخال عدد الأيام في هذا البرنامج",
        "Please select exercises under the day": "يرجى تحديد التمارين في اليوم",
        "Please select currency": "يرجى تحديد العملة",
        "Please select Type": "يرجى تحديد النوع",
        "Please select a program": "يرجى تحديد برنامج",
        "Please select days": "يرجى تحديد الأيام",
        "Failed to upload": "فشل في التحميل",
        "Failed to upload image. Please try again": "فشل في تحميل الصورة. يرجى المحاولة مرة أخرى",
        "Failed to upload video. Please try again": "فشل في تحميل الفيديو. يرجى المحاولة مرة أخرى",
        "Exercise Library Delete!": "حذف مكتبة التمرين!",
        "Exercise Library Delete successfully": "تم حذف مكتبة التمرين بنجاح",
        "File size is high": "حجم الملف كبير",
        "Permission not satisfied": "غير مرضية الإذن",
        "Camera not available on device": "الكاميرا غير متاحة على الجهاز",
        "Camera permission denied": "تم رفض إذن الكاميرا",
        "Please provide us the camera permission to capture the image": "يرجى توفير إذن الكاميرا لنا لالتقاط الصورة",
        "Upload file with maximum size of 5 MB for Images and 30MB for video": "قم بتحميل ملف بحجم أقصى قدره 5 ميجابايت للصور و 30 ميجابايت للفيديو",
        "Exercise Program Delete!": "حذف برنامج التمرين!",
        "Exercise Program Delete successfully": "تم حذف برنامج التمرين بنجاح",
        "Discount maximum be 100": "يجب أن يكون الخصم الأقصى 100",
        "Discount must be zero": "يجب أن يكون الخصم صفر",
        "Invalid Discount Percentage": "نسبة خصم غير صحيحة",
        "Price must be greater than zero": "يجب أن يكون السعر أكبر من الصفر",
        "Invalid Price": "سعر غير صحيح",
        "Exercise Library Updated!": "تحديث مكتبة التمرين!",
        "Exercise Library Updated successfully": "تم تحديث مكتبة التمرين بنجاح",
        "Exercise Library Created!": "إنشاء مكتبة التمرين!",
        "Exercise Library Created successfully": "تم إنشاء مكتبة التمرين بنجاح",
        "Exercise Library Duplicate!": "تكرار مكتبة التمرين!",
        "Exercise Library Duplicate successfully": "تم تكرار مكتبة التمرين بنجاح",
        "Exercise Program Updated!": "تحديث برنامج التمرين!",
        "Exercise Program Updated successfully": "تم تحديث برنامج التمرين بنجاح",
        "Exercise Program Created!": "إنشاء برنامج التمرين!",
        "Exercise Program Created successfully": "تم إنشاء برنامج التمرين بنجاح",
        "No Of Days Added!": "تمت إضافة عدد الأيام!",
        "No Of Days Added successfully": "تمت إضافة عدد الأيام بنجاح",
        "Day Name Updated!": "تم تحديث اسم اليوم!",
        "Day Name Updated successfully": "تم تحديث اسم اليوم بنجاح",
        "Warmup Added!": "تمت إضافة التمهيد!",
        "Warmup Added successfully": "تمت إضافة التمهيد بنجاح!",
        "Cool down Added!": "تمت إضافة التبريد!",
        "Cool down Added successfully": "تمت إضافة التبريد بنجاح!",
        "Exercise Added!": "تمت إضافة التمرين!",
        "Exercise Added successfully": "تمت إضافة التمرين بنجاح!",
        "Plan & package Updated!": "تم تحديث",
        "Plan & package Updated successfully": "تم تحديث الخطة والباقة بنجاح!",
        "Plan & package Created!": "تم إنشاء الخطة والباقة!",
        "Plan & package Created successfully": "تم إنشاء الخطة والباقة بنجاح!",
        "Week And Days Added!": "تمت إضافة الأسبوع والأيام!",
        "Week And Days Added successfully": "تمت إضافة الأسبوع والأيام بنجاح!",
        "Program Added!": "تمت إضافة البرنامج!",
        "Program Added successfully": "تمت إضافة البرنامج بنجاح!",
        "Week Duplicate!": "تكرار الأسبوع!",
        "Week Duplicate successfully": "تم تكرار الأسبوع بنجاح!",
        "Week Delete!": "حذف الأسبوع!",
        "Week Delete successfully": "تم حذف الأسبوع بنجاح!",
        "Password must be of minimum 8 characters!!": "يجب أن تحتوي كلمة المرور على الأقل على 8 أحرف!",
        "Please enter a password.": "يرجى إدخال كلمة مرور",
        "Please enter a password different from the last one": "يرجى إدخال كلمة مرور",
        "Please enter a confirmation password.": "يرجى إدخال تأكيد كلمة المرور",
        "Password updated": "تم تحديث كلمة المرور",
        "Your password updated successfully": "تم تحديث كلمة المرور بنجاح",
        "Current Password": "تم تحديث كلمة المرور بنجاح",
        "Questionnaire": "استبيان",
        "Password must be of minimum 8 character": "يجب أن تحتوي كلمة المرور على الأقل على 8 أحرف",
        "New Password": "كلمة مرور جديدة",
        "Please enter a confirm password'": "يرجى إدخال تأكيد كلمة المرور",
        "Please enter you contact details for registration purpose": "يرجى إدخال تفاصيل الاتصال الخاصة بك لأغراض التسجيل",
        "All fields are mandatory!!": "جميع الحقول إلزامية !!",
        "Welcome back, Please enter your login details to continue": "مرحبًا، يرجى إدخال تفاصيل تسجيل الدخول الخاصة بك للمتابعة",
        "Login": "تسجيل الدخول",
        "Password(minimum 8 characters)": "كلمة المرور (الحد الأدنى 8 أحرف)",
        "Forgot password?": "نسيت كلمة المرور؟",
        "Don't have an account ?": "ليس لديك حساب؟",
        "Signup Here": "سجل هنا",
        "Current Weight?": "الوزن الحالي؟",
        "Skip": "تخطى",
        "Move": "حركة",
        "Issue Title": "عنوان المشكلة",
        "Issue Details": "تفاصيل المشكلة",
        "Upload image and pdf": "تحميل الصورة والملف النصي",
        "Logout": "تسجيل الخروج",
        "Are you sure to logout?": "هل أنت متأكد من تسجيل الخروج؟",
        "My Orders / Plans": "طلباتي / خططي",
        "Workout, Nutrition and Products": "تمرين، تغذية ومنتجات",
        "Promotions & Notifications": "العروض والإشعارات",
        "Change application language": "تغيير لغة التطبيق",
        "Change password": "تغيير لغة التطبيق",
        "Update your password": "تحديث كلمة المرور",
        "Delete Account": "حذف الحساب",
        "Permanently Delete Your Account": "حذف حسابك نهائيًا",
        "Add to Planner": "إضافة إلى المخطط",
        "History": "التاريخ",
        "Training Programs": "برامج التدريب",
        "Products": "المنتجات",
        "Nutrition Programs": "برامج التغذية",
        "Well Done!": "عمل رائع!",
        "Please continue with your next workout": "يرجى الاستمرار مع تمرينك القادم",
        "Done": "تم",
        "Logs": "سجلات",
        "Notes": "ملاحظات",
        "Start Typing": "ابدأ الكتابة",
        "Mark As Completed": "وضع علامة كمكتمل",
        "Add Workout Log": "إضافة سجل تمرين",
        "Find workouts": "العثور على تمارين",
        "Group": "مجموعة",
        "Progress History": "سجل التقدم",
        "No Progress History": "لا توجد سجلات تقدم",
        "Progress Updated": "تم تحديث التقدم",
        "Your Progress Updated Successfully": "تم تحديث التقدم بنجاح",
        "Please select measurement type and its value": "يرجى تحديد نوع القياس وقيمته",
        "Up to 4 images and optional to upload": "يصل إلى 4 صور واختياري للتحميل",
        "Please add your weight in kg": "يرجى إضافة وزنك بالكيلوغرام",
        "Please select a unit": "يرجى تحديد وحدة القياس",
        "Please enter a note": "يرجى إدخال ملاحظة",
        "Weekly": "أسبوعيا",
        "Monthly": "شهريا",
        "Full Period": "فترة كاملة",
        "Right Arm": "الذراع الأيمن",
        "Left Arm": "الذراع الأيسر",
        "Right Leg": "الساق اليمنى",
        "Left Leg": "الساق اليسرى",
        "Hip": "الورك",
        "Weight Required": "الوزن مطلوب",
        "No orders exist": "لا توجد طلبات",
        "No weeks available": "لا توجد أسابيع متاحة",
        "No workouts available": "لا توجد تمارين متاحة",
        "No exercise available": "لا توجد تمارين متاحة",
        "No Questions": "لا توجد أسئلة",
        "Are you sure to delete this custom exercise": "هل أنت متأكد من حذف هذا التمرين المخصص؟",
        "Workouts not available": "التمارين غير متاحة",
        "Your payment Initiation failed. Please try again later. Error Code": "فشل بدء الدفع الخاص بك. يرجى المحاولة مرة أخرى في وقت لاحق. رمز الخطأ",
        "Added workout log": "تمت إضافة سجل التمرين",
        "Workout log added successfully": "تمت إضافة سجل التمرين بنجاح",
        "Added workout note": "تمت إضافة ملاحظة التمرين",
        "Workout note added successfully": "تمت إضافة ملاحظة التمرين بنجاح",
        "Feed": "التغذية",
        "Water Goal": "كمية الماء المطلوبة",
        "Steps Goal": "عدد الخطوات المطلوب",
        "Energy": "الطاقة",
        "Sleep": "النوم",
        "Stress": "التوتر",
        "No Food found. under your Food will be listed here": "لم يتم العثور على أي طعام. سيتم إدراج طعامك هنا",
        "No Recipes found. under your Recipes will be listed here": "لم يتم العثور على أي وصفات. سيتم إدراج وصفاتك هنا",
        "create a New Food": "إنشاء طعام جديد",
        "create a New Recipe": "إنشاء وصفة جديدة",
        "Extra Details": "تفاصيل إضافية",
        "Macro Nutrients": "العناصر الغذائية الأساسية",
        "create a nutrition program": "إنشاء برنامج تغذية",
        "Create Program": "إنشاء برنامج",
        "Please add an issue title": "يرجى إضافة عنوان للمشكلة",
        "Please add your issue details": "يرجى إضافة تفاصيل مشكلتك",
        "Nutrition Program Delete!": "حذف برنامج التغذية!",
        "Nutrition Program Delete successfully": "تم حذف برنامج التغذية بنجاح",
        "Food Delete!": "حذف الطعام!",
        "Food Delete successfully": "تم حذف الطعام بنجاح",
        "select one item!": "حدد عنصر واحد!",
        "Please select at least on item": "يُرجَى تحديد عنصر واحد على الأقل",
        "Recipe Delete!": "حذف الوصفة!",
        "Recipe Delete successfully": "تم حذف الوصفة بنجاح",
        "Joined": "تم الانضمام",
        "Progress": "التقدم المُحرَز",
        "View Steps": "عرض الخطوات",
        "Plans": "الخطط",
        "Kg": "كجم",
        "Send message": "إرسال رسالة",
        "DOB": "تاريخ الميلاد",
        "Height": "الطول",
        "Activity Level": "مستوى النشاط",
        "Age": "العمر",
        "Profile": "الملف الشخصي",
        "Subscription": "الاشتراك",
        "cm": "سم",
        "Name": "الاسم",
        "Exercises": "التمارين",
        "Issue added": "تمت إضافة المشكلة",
        "issue updated successfully. Please wait for replay": "تم تحديث المشكلة بنجاح يرجى الانتظار للرد",
        "Are you sure to delete?": "هل أنت متأكد من الحذف؟",
        "Issue": "المشكلة",
        "Reply": "الرد",
        "Please add Title": "أضف عنوان",
        "Please add your issue": "أضف مشكلتك",
        "Goals": "الأهداف",
        "ml": "مل",
        "Target": "الهدف",
        "Water": "الماء",
        "Steps": "الخطوات",
        "Save Target": "حفظ الهدف",
        "Today": "اليوم",
        "View": "عرض",
        "Create": "إنشاء",
        "Upload Images and Videos": "تحميل الصور والفيديوهات",
        "Add Programs": "أضف برامج",
        "10% or however much percent will be deducted form the total": "سيتم خصم 10% أو أيًا كانت النسبة من المجموع الكلي",
        "Food": "الطعام",
        "Recipes": "الوصفات",
        "Serving Size": "حجم وجبة الطعام",
        "No Of Serving": "عدد وجبات الطعام",
        "Protein": "البروتين",
        "Fat": "الدهون",
        "Carbohydrates": "الكربوهيدرات",
        "Sugar": "السكر",
        "Saturated Fat": "الدهون المشبعة",
        "Polyunsaturated": "الدهون المتعددة غير المشبعة",
        "Sodium": "الصوديوم",
        "Potassium": "البوتاسيوم",
        "Calories": "السعرات الحرارية",
        "Add Food": "أضف طعام",
        "Add Meal": "أضف وجبة",
        "Carbs": "الكربوهيدرات",
        "Methods": "الإجراءات",
        "Recipe": "الوصفة",
        "Chat": "الدردشة",
        "Ingredients": "المكونات",
        "Program Day": "يوم البرنامج",
        "Target Added": "تمت إضافة الهدف",
        "Target Created Successfully": "تم إنشاء الهدف بنجاح",
        "Nutrition Program Created!": "تم إنشاء برنامج التغذية!",
        "Nutrition Program Created successfully": "تم إنشاء برنامج التغذية بنجاح",
        "Nutrition Program Updated!": "تم تحديث برنامج التغذية!",
        "Nutrition Program Updated successfully": "تم تحديث برنامج التغذية بنجاح",
        "Nutrition Program Meal  Created!": "تم إنشاء وجبة برنامج التغذية!",
        "Nutrition Program Meal Created successfully": "تم إنشاء وجبة برنامج التغذية بنجاح",
        "Recipe Created!": "تم إنشاء الوصفة!",
        "Recipe Created successfully": "تم إنشاء الوصفة بنجاح",
        "Recipes Updated!": "تم تحديث الوصفات!",
        "Recipes Updated successfully": "تم تحديث الوصفات بنجاح",
        "Meal Add!": "إضافة وجبة!",
        "Meal Add successfully": "تمت إضافة الوجبة بنجاح",
        "Not added any logs for this exercise": "لم تتم إضافة أي سجلات لهذا التمرين",
        "Please enter a Name": "أدخل اسمك",
        "Please enter a Calories": "أدخل السعرات الحرارية",
        "Please enter a Serving Size": "أدخل حجم وجبة الطعام",
        "Please enter a No Of Serving": "أدخل عدد وجبات الطعام",
        "Please enter a Protein": "أدخل نسبة البروتين",
        "Please enter a Carbs": "أدخل نسبة الكربوهيدرات",
        "Please enter a Fat": "أدخل نسبة الدهون",
        "Please enter a Sugar": "أدخل نسبة السكر",
        "Please enter a SaturatedFat": "أدخة نسبة الدهون المشبعة",
        "Please enter a Polyunsaturated": "أدخل نسبة الدهون المتعددة غير المشبعة",
        "Please enter a Sodium": "أدخل نسبة الصوديوم",
        "Please enter a Potassium": "أدخل نسبة البوتاسيوم",
        "Food Library Delete!": "حذف مكتبة الطعام!",
        "Food Library Delete successfully": "تم حذف مكتبة الطعام بنجاح",
        "Food Library Updated!": "تم تحديث مكتبة الطعام!",
        "Food Library Updated successfully": "تم تحديث مكتبة الطعام بنجاح",
        "Food Library Created!": "تم إنشاء مكتبة الطعام!",
        "Food Library Created successfully": "تم إنشاء مكتبة الطعام بنجاح",
        "No Clients exist": "لا يوجد عملاء",
        "Please Enter Water Goal": "أدخل كمية الماء المطلوبة",
        "Please Enter Steps Goal": "أدخل عدد الخطوات المطلوب",
        "please enter valid numberPlease add method": "أدخل رقم صالح، وبرجاء إضافة الإجراء",
        "Please add method": "أضف الإجراء",
        "please enter valid number": "أدخل رقم صالح",
        "No Messages Found": "لم يتم العثور على أية رسائل",
        "No Previous Chat": "لا توجد دردشة سابقة",
        "something went wrong": "حدث خطأ ما",
        "Multiple pickers were opened, only the last will be considered": "تم فتح العديد من الخيارات، سيتم اعتماد الخيار الأخير فقط",
        "Choose Files": "اختر الملفات",
        "Check your Email": "تحقق من بريدك الإلكتروني",
        "Reset otp send to your email id": "أعد تعيين رمز التحقق (OTP) الذي تم إرساله إلى بريدك الإلكتروني",
        "Password Reset": "أعد تعيين كلمة المرور",
        "Enter your email address to receive a code reset your password.": "أدخل عنوان بريدك الإلكتروني لتلقي رمز إعادة تعيين كلمة مرورك",
        "Enter The Verification Code That we send to your": "أدخل رمز التحقق الذي أرسلناه إلى",
        "be careful not to share code with any one": "كن حذرًا ولا تشارك الرمز مع أي شخص",
        "You haven't received the code?": "لم تتلقَّ الرمز؟",
        "Enter The Code": "أدخل الرمز",
        "Successfully Verify Your Email": "تم التحقق من بريدك الإلكتروني بنجاح",
        "Shop": "المتجر",
        "Log": "السجل",
        "Your Coach": "مدربك",
        "Connect": "اتصال",
        "My Profile": "ملفي الشخصي",
        "My information": "معلوماتي",
        "Settings": "الإعدادات",
        "Notifications": "الإشعارات",
        "Language": "اللغة",
        "ft": "قدم",
        "lbs": "رطل",
        "Current Order": "الطلب الحالي",
        "Choose Start Date": "اختر تاريخ البدء",
        "Order ID -": "رقم تعريف الطلب -",
        "No of weeks": "عدد الأسابيع",
        "Start Date": "تاريخ البدء",
        "General info": "معلومات عامة",
        "Order No": "رقم الطلب",
        "Payment Status": "حالة الدفع",
        "Total": "الإجمالي",
        "VAT": "ضريبة القيمة المضافة",
        "Total Price": "السعر الإجمالي",
        "Mark as Default": "تعيين كافتراضي",
        "Created On:": "تم الإنشاء في:",
        "Enter extra set name": "أدخل اسم المجموعة الإضافية",
        "Enter extra set value": "أدخل قيمة المجموعة الإضافية",
        "Updating": "جارٍ التحديث",
        "Updating Exercise Order": "جارٍ تحديث إعداد التمرين",
        "Moving": "جارٍ النقل",
        "Updating Set Order": "جارٍ تحديث ترتيب المجموعة",
        "Move Up": "تحريك للأعلى",
        "Move Down": "تحريك للأسفل",
        "Day Group": "مجموعة اليوم",
        "Record": "السجل",
        "Unit": "الوحدة",
        "Delete Exercise": "حذف التمرين",
        "Muscle Group": "مجموعة العضلات",
        "Rep Max history Function": "خاصية سجل الحد الأقصى للتكرار",
        "Workouts Filter": "مرشح التدريبات",
        "Primary Muscles": "العضلات الأساسية",
        "Secondary Muscles": "العضلات الثانوية",
        "Intermitent fasting": "الصيام المتقطع",
        "Goal": "الهدف",
        "I would like to...": "أود أن...",
        "Perform Better": "الأداء بشكل أفضل",
        "Gain Weight": "زيادة الوزن",
        "Find Plan": "العثور على خطة",
        "Ketogenic": "حمية الكيتو",
        "New": "جديد",
        "Not sure which plan ?": "لستَ متأكدًا من الخطة المناسبة؟",
        "Find out now": "اكتشف الآن",
        "New Program": "برنامج غذائي جديد",
        "Intermittent": "متقطع",
        "Buy Now": "اشترِ الآن",
        "Coach": "المدرب",
        "Packages": "الحزم",
        "Verified": "تم التحقق",
        "% off": "% خصم",
        "Next": "التالي",
        "issue updated": "تم تحديث المشكلة",
        "issue updated successfully": "تم تحديث المشكلة بنجاح",
        "Strength Calculator": "حاسبة القوة",
        "Lift": "الرفع",
        "Repetitions": "التكرارات",
        "Calculate": "احسب",
        "Percentage of 1RM": "نسبة من الحد الأقصى للمرة الواحدة",
        "Lift Weight": "وزن الرفع",
        "Typing....": "جارٍ الكتابة...",
        "Hours": "الساعات",
        "Verify OTP": "تحقق من رمز التحقق (OTP)",
        "Resend": "إعادة الإرسال",
        "Please add your measurements": "أضف قياسات جسمك",
        "Standard": "قياسي",
        "Vegan": "نباتي",
        "Vegetarian": "نباتي (يأكل منتجات الألبان)",
        "Pescatarian": "نباتي (يأكل الأسماك)",
        "Filter": "فلتر",
        "Breakfast": "الإفطار",
        "Snack": "وجبة خفيفة",
        "Dinner": "العشاء",
        "Lunch": "الغداء",
        "Post Workout": "بعد التمرين",
        "Select": "اختر",
        "Sub Total": "المجموع الفرعي",
        "Latest": "الأحدث",
        "Clear All": "مسح الكل",
        "No Notification": "لا توجد إشعارات",
        "No Programs Available": "لا توجد برامج متاحة",
        "Please add a title": "أضف عنوان",
        "Please choose type to continue": "اختر النوع للاستمرار",
        "Please add measurement for selected type": "أضف قياس للنوع المُحدد",
        "Notification  Delete!": "حذف الإشعار!",
        "Notification  Delete successfully": "تم حذف الإشعار بنجاح",
        "Training Log": "سجل التدريب",
        "Nadena Shop": "متجر نادينا",
        "Order Details": "تفاصيل الطلب",
        "Update Measurment": "تحديث القياس",
        "Trainers": "المدربون",
        "Trainer Details": "تفاصيل المدرب",
        "Nutrition Program": "برنامج التغذية",
        "Macro Calculator": "حاسبة عناصر التغذية الأساسية",
        "Report Issue": "الإبلاغ عن مشكلة",
        "Workouts By Day": "التدريبات حسب اليوم",
        "SetsNotification": "إشعارات المجموعات",
        "Preview": "معاينة",
        "Offer": "عرض",
        "Add Goals": "إضافة أهداف",
        "Add Target": "إضافة هدف محدد",
        "Confirm OTP": "تأكيد رمز OTP",
        "Nutrition Details": "تفاصيل التغذية",
        "Enter your target": "أدخل هدفك المحدد",
        "Questions to evaluate": "أسئلة للتقييم",
        "Contact details & Personal information": "تفاصيل الاتصال والمعلومات الشخصية",
        "Start Typing...": "ابدأ الكتابة...",
        "Select Type": "اختر النوع",
        "Measurement": "القياس",
        "Add Measurement": "إضافة قياس",
        "Update Progress": "تحديث التقدم",
        "Please choose date of birth.": "حدد تاريخ الميلاد.",
        "Please enter your email address": "أدخل عنوان بريدك الإلكتروني",
        "Please selectGen a Gender": "حدد الجنس",
        "Enter your Name": "أدخل اسمك",
        "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
        "Please enter your height": "أدخل طولك",
        "Please enter your Weight": "أدخل وزنك",
        "Please select a Profile Image": "حدد صورة للملف الشخصي",
        "Enter lift": "أدخل الوزن",
        "Enter Repetition": "أدخل التكرار",
        "Strength Added": "تمت إضافة القوة",
        "Strength Added successfully": "تمت إضافة القوة بنجاح",
        "Please Enter your Water Goal": "أدخل الكمية المطلوبة من الماء",
        "Goal  Added!": "تمت إضافة الهدف!",
        "Goal Add successfully": "تمت إضافة الهدف بنجاح",
        "Please enter your emailPlease enter a valid email.": "برجاء إدخال بريدك الإلكتروني صالح",
        "Please enter a Status": "أدخل الحالة",
        "FALSE": "خطأ",
        "TRUE": "صحيح",
        "Status": "الحالة"
    }
;

let result = matchArrays(array1, array2);
let jsonResult = JSON.stringify(result);
console.log(jsonResult); // {"createFood":"Create A New Food"}
